### ISSUE TITLE
logr v1.0.0-rc1 includes breaking changes

### ISSUE THREAD

**Issue by thockin** [iand/logfmtr#1]
logr made BREAKING CHANGES for implementations to prep for 1.0.0

Here's the glogr PR that adopts the new logr API changes: go-logr/glogr#13 - this includes a bunch of perf-related changes too (sorry).

The changes are not THAT complicated. Please feel free to shout if they don't make sense.

**Comment by iand** [comment]
Thanks for the heads up! I'll work on aligning with the new API

**Comment by thockin** [comment]
I'll work on a more surgical change for zapr which should be a better
example.  Holler if anything is unclear.

**Comment by thockin** [comment]
https://github.com/go-logr/zapr/pull/28 is another example

**Comment by iand** [comment]
Updated in https://github.com/iand/logfmtr/pull/2

**Comment by thockin** [comment]
logr v1.0.0 has been tagged.  No changes since rc1.
